#!/bin/bash
# Copyright 2012 Christoph Langner
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Get url to asx video stream out of the no flash version of the zdf mediathek
url_noflash="$1"
url_stream=$(curl -s ${url_noflash} | grep asx | grep -o 'http://[^"]*')


# If filename is empty, get name out of url
filename=$2
if [ -z ${filename} ]; then
	filename=$(echo ${url_noflash} | cut -d/ -f8- | cut -d? -f1)".wmv"
fi 

# Get stream and save it to disk
curl -s ${url_stream} | grep mms: | cut -d\" -f2 | xargs -n1 mplayer -dumpstream -dumpfile ${filename}

